@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant "organization\n:Organization" as ORG

@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources \n Manager (HRM)" as HRM
participant ":AssignJobUI" as UI
participant ":AssignJobController" as CTRL
participant "repositories\n:Repositories" as PLAT

participant "CollaboratorsRepository" as CollaboratorsRepository

activate HRM

        HRM -> UI : asks to add a job

        activate UI


            UI -> CTRL** : create

            UI -> CTRL : getCollaborators()
            activate CTRL
 ref over CTRL

 Get Collaborator

 end

                CTRL --> UI : collaboratorsList
            deactivate CTRL

            UI --> HRM : shows collaborators to create\n a new job
        deactivate UI

    HRM -> UI : choose collaborator
    activate UI

   UI -> CTRL : getJob (jobName)
           activate CTRL

ref over CTRL

 Get Skill

 end

         CTRL --> UI : jobList
         deactivate CTRL

         UI --> HRM : show jobs list
         deactivate UI

         HRM -> UI : choose job to assign
         activate UI

         UI -> CTRL : assignJob(jobName))
         activate CTRL

         CTRL -> PLAT : assignJob(jobName))
         activate PLAT

         PLAT -> CollaboratorsRepository : assignJob(jobName))
         activate CollaboratorsRepository

         ref over CollaboratorsRepository



         Assign Job



          end ref

         CollaboratorsRepository --> PLAT : Job
         deactivate CollaboratorsRepository

         PLAT --> CTRL : job
         deactivate PLAT

         CTRL --> UI : job
         deactivate CTRL

         UI --> HRM : displays operation success
         deactivate UI

         deactivate HRM

 @enduml