@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Green Space\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Ask to add a new entry to the To-Do List
    activate System

        System --> Employee : requests data (i.e description, urgency, duration, green space)
    deactivate System

    Employee -> System : inputs requested data
    activate System

        System --> Employee : processes input, records the new entry, and\ndisplays operation success message
    deactivate System

@enduml