@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Green Space\nManager" as Employee
 GSM -> System : asks to add a new Task entry to the To-Do List
    activate System

        System --> GSM : displays list of green spaces
    deactivate System

    GSM -> System : selects a green space
    activate System

        System --> GSM : requests the details of the task
    deactivate System

    GSM -> System : provides task details
    activate System

        System --> GSM : adds task to the To-Do List and displays operation success
    deactivate System

@enduml