@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Green Space\nManager" as Manager
participant ":System" as System

activate GSM

    GSM -> System : asks to register a new green space
    activate System

        System --> GSM : request details of the green space(garden, medium-sized park or large-sized park)\n and respctive area
    deactivate System

    GSM -> System : provides green space details
       activate System

       System --> GSM : registers green spaces and their respective areas, displaying operation success.
           deactivate System


@enduml