@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Green Space\nManager" as Manager
participant ":System" as System

activate GSM

    Manager -> System : asks to view data relative to the usage of park\nequipments
    activate System

        System --> Manager : presents pie chart representing, in percentage,\nthe amount that each equipment is used
    deactivate System

@enduml