@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Fleet\nManager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : asks to list vehicles requiring check-up
    activate System

        System --> Manager : presents list of vehicles whose check-up date is\ndue or past
    deactivate System

@enduml