@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "skillRepository" as SR
participant "skill\n:Skill" as S

autonumber 11
-> SR: registerSkill(name)

autonumber 11.1
activate SR
    group Register SKills

        SR -> S**: register(name)
        SR -> SR: addSkill (skill)

        activate SR
            SR -> SR: confirmSkill(skill)
            activate SR

    end

    autonumber 12
    <-- SR : skill
deactivate SR


@enduml