@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resource Manager" as HRM
participant ":RegisterSkillUI" as UI
participant ":RegisterSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository" as SR
participant "skill\n:Skill" as S


activate HRM

        HRM -> UI : asks to register a new skill

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL

            UI --> HRM : request skill name

         deactivate UI

            HRM --> UI : Types requested data

         activate UI

           UI --> HRM : Shows all data and request confirmation

         deactivate UI

            HRM --> UI : Confirm skill

         activate UI

            UI -> CTRL : RegisterSkill(name)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton


            CTRL-> PLAT : getSkillRepository()
                        activate PLAT

            PLAT --> CTRL : skillRepository
                         deactivate PLAT

            CTRL -> SR : registerSkill(name)
                        activate SR

            SR -> S : register(name)


            SR ->SR : addSkill(name)

            SR->SR : confirmSkill(skill)

            SR--->CTRL : skill

                        deactivate SR
            CTRL ---> UI : skill
                        deactivate CTRL

            UI ---> HRM : displays operation success
                        deactivate UI



@enduml