@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":AuthenticationRepository" as AuthenticationRepository
participant ":GreenSpaceController" as GreenSpaceController
participant ":Repositories" as Repositories
participant "repositories:\nRepositories" as RepositoriesInstance
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "greenSpaceTypeRepository:\nGreenSpaceTypeRepository" as GreenSpaceTypeRepository
participant "GreenSpace" as GreenSpace
participant "Address" as Address
participant "GreenSpaceDTO" as GreenSpaceDTO
participant "GreenSpaceMapper" as GreenSpaceMapper

activate GSM

    GSM -> UI : asks to register a new green space

        activate UI

            UI --> GSM : request details of the green space(garden, medium-sized park or large-sized park)\n and respctive area
        deactivate System

        GSM -> UI : provides green space details


           UI --> GSM : registers green spaces and their respective areas, displaying operation success.




        UI -> AuthenticationRepository : getCurrentUserSession().getUserId().getEmail()
        activate AuthenticationRepository

            AuthenticationRepository --> UI : email
        deactivate AuthenticationRepository

        UI -> GreenSpaceController : registerGreenSpace(name, type, area, email, address)
        activate GreenSpaceController

            GreenSpaceController -> Repositories : getInstance()
            activate Repositories

                Repositories --> GreenSpaceController : instance
            deactivate Repositories

            GreenSpaceController -> RepositoriesInstance : getGreenSpaceRepository()
            activate RepositoriesInstance

                RepositoriesInstance --> GreenSpaceController : greenSpaceRepository
            deactivate RepositoriesInstance

            GreenSpaceController -> GreenSpaceMapper : getMapper()
            activate GreenSpaceMapper

                GreenSpaceMapper --> GreenSpaceController : mapper
            deactivate GreenSpaceMapper

            GreenSpaceController -> "GreenSpaceMapper" : objectToDTO(name, type, area, email, address)
            activate GreenSpaceMapper

                "GreenSpaceMapper" --> GreenSpaceController : greenSpaceDTO
            deactivate "GreenSpaceMapper"

            GreenSpaceController -> GreenSpaceRepository : addGreenSpace(greenSpaceDTO)
            activate GreenSpaceRepository

                GreenSpaceRepository -> GreenSpace : registerGreenSpace(greenSpaceDTO)
                activate GreenSpace
                GreenSpace --> GreenSpace : addGreenSpace()
                GreenSpace --> GreenSpace : validateGreenSpace()

                    GreenSpace --> GreenSpaceRepository : greenSpace
                deactivate GreenSpace
                GreenSpaceRepository --> GreenSpaceController : greenSpace
            deactivate GreenSpaceRepository

            GreenSpaceController --> UI : greenSpace
        deactivate GreenSpaceController

        UI --> GSM : displays operation success
    deactivate UI
    deactivate GSM
@enduml
