@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto


class "GreenSpace" {
    -String name
    -String address
    -int area
    -GreenSpaceType type
    -String creatorEmail

    +GreenSpace(String name, String address, int area, GreenSpaceType type)


}

class "GreenSpaceType" {
    GARDEN
    MEDIUM_SIZE
    LARGE_SIZE
}

class "RegisterGreenSpaceController" {
    -GreenSpaceRepository greenSpaceRepository

    +RegisterGreenSpaceController()
    +Optional<GreenSpace> registerGreenSpace(GreenSpaceDTO greenSpaceDTO)
}

class "GreenSpaceRepository" {
    +GreenSpaceRepository()
    +GreenSpace(String name, String address, int area, GreenSpaceType type)

}

class "GreenSpaceDTO" {
    +String name
    +String address
    +int area
    +GreenSpaceType type

}

class "GreenSpaceMapper" {
    +GreenSpaceDTO objectToDTO(GreenSpace greenSpace) : GreenSpaceDTO
    +GreenSpace DTOToObject(GreenSpaceDTO greenSpaceDTO) : GreenSpace
    +static GreenSpaceMapper getMapper() : GreenSpaceMapper
}

class "RegisterGreenSpaceUI" {
    - name
    -address
    - area
    -type

}

GreenSpaceRepository --> "contains and manages" GreenSpace
RegisterGreenSpaceController --> "has" GreenSpaceRepository
RegisterGreenSpaceUI --> "uses" RegisterGreenSpaceController
RegisterGreenSpaceUI --> "creates and uses" GreenSpaceDTO
GreenSpace --> "contains a" GreenSpaceType
GreenSpaceDTO --> "contains " GreenSpace
GreenSpaceMapper --> "converts" GreenSpace
GreenSpaceMapper --> "converts" GreenSpaceDTO
RegisterGreenSpaceController --> "uses" GreenSpaceMapper
@enduml
