@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":AuthenticationRepository" as AuthenticationRepository
participant ":GreenSpaceController" as GreenSpaceController
participant ":Repositories" as Repositories
participant "repositories:\nRepositories" as RepositoriesInstance
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "greenSpaceTypeRepository:\nGreenSpaceTypeRepository" as GreenSpaceTypeRepository
participant "GreenSpace" as GreenSpace
participant "Address" as Address
participant "GreenSpaceDTO" as GreenSpaceDTO
participant "GreenSpaceMapper" as GreenSpaceMapper

activate GSM

    GSM -> UI : asks to register a new green space
    activate UI

        UI --> GSM : requests details of the green space

    deactivate UI

    GSM -> UI : provides green space details (name, type, area, address)
    activate UI

        UI -> GreenSpaceController : getGreenSpaceTypes()
        activate GreenSpaceController

            GreenSpaceController -> Repositories : getInstance()
            activate Repositories

                Repositories --> GreenSpaceController : instance
            deactivate Repositories

            GreenSpaceController -> RepositoriesInstance : getGreenSpaceTypeRepository()
            activate RepositoriesInstance

                RepositoriesInstance --> GreenSpaceController : greenSpaceTypeRepository
            deactivate RepositoriesInstance

            GreenSpaceController -> GreenSpaceTypeRepository : getGreenSpaceTypes()
            activate GreenSpaceTypeRepository

                GreenSpaceTypeRepository --> GreenSpaceController : types
            deactivate GreenSpaceTypeRepository

            GreenSpaceController --> UI : types
        deactivate GreenSpaceController

        UI --> GSM : displays types of green spaces
    deactivate UI

    GSM -> UI : selects type of green space
    activate UI

        UI --> GSM : asks for area of the park
    deactivate UI

    GSM -> UI : provides area of the park
    activate UI

        UI -> AuthenticationRepository : getCurrentUserSession().getUserId().getEmail()
        activate AuthenticationRepository

            AuthenticationRepository --> UI : email
        deactivate AuthenticationRepository

        UI -> GreenSpaceController : registerGreenSpace(name, type, area, email, address)
        activate GreenSpaceController

            GreenSpaceController -> Repositories : getInstance()
            activate Repositories

                Repositories --> GreenSpaceController : instance
            deactivate Repositories

            GreenSpaceController -> RepositoriesInstance : getGreenSpaceRepository()
            activate RepositoriesInstance

                RepositoriesInstance --> GreenSpaceController : greenSpaceRepository
            deactivate RepositoriesInstance

            GreenSpaceController -> GreenSpaceMapper : getMapper()
            activate GreenSpaceMapper

                GreenSpaceMapper --> GreenSpaceController : mapper
            deactivate GreenSpaceMapper

            GreenSpaceController -> "GreenSpaceMapper" : objectToDTO(name, type, area, email, address)
            activate GreenSpaceMapper

                "GreenSpaceMapper" --> GreenSpaceController : greenSpaceDTO
            deactivate "GreenSpaceMapper"

            GreenSpaceController -> GreenSpaceRepository : addGreenSpace(greenSpaceDTO)
            activate GreenSpaceRepository

                GreenSpaceRepository -> GreenSpace : registerGreenSpace(greenSpaceDTO)
                activate GreenSpace
                GreenSpace --> GreenSpace : addGreenSpace()
                GreenSpace --> GreenSpace : validateGreenSpace()

                    GreenSpace --> GreenSpaceRepository : greenSpace
                deactivate GreenSpace
                GreenSpaceRepository --> GreenSpaceController : greenSpace
            deactivate GreenSpaceRepository

            GreenSpaceController --> UI : greenSpace
        deactivate GreenSpaceController

        UI --> GSM : displays operation success
    deactivate UI
    deactivate GSM
@enduml
