@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto



class "GreenSpace" {
    -name : String
    -address : String
    -area : int
    -type : GreenSpaceType
    -creatorName : String
    -creatorEmail : String
    +GreenSpace(name : String, address : String, area : int, type : GreenSpaceType)
    +getType() : GreenSpaceType
    +getArea() : int
    +getName() : String
    +getAddress() : String
    +toString() : String
    +isCreatedBy(name : String, email : String) : boolean
}

class "GreenSpaceType" {
    GARDEN
    MEDIUM_SIZE
    LARGE_SIZE
    +getAllTypes() : ArrayList<GreenSpaceType>
}

class "RegisterGreenSpaceController" {
    -GreenSpaceRepository : GreenSpaceRepository
    +RegisterGreenSpaceController()
    +registerGreenSpace(name : String, address : String, area : int, type : GreenSpaceType) : Optional<GreenSpace>
}

class "GreenSpaceRepository" {
    -greenSpaces : ArrayList<GreenSpace>
    +GreenSpaceRepository()
    +add(name : String, address : String, area : int, type : GreenSpaceType) : Optional<GreenSpace>
    +getGreenSpacesManagedByUser() : Optional<ArrayList<GreenSpace>>
}

class "GreenSpaceDTO" {
    +name : String
    +address : String
    +area : int
    +type : GreenSpaceType
    +attachedGreenSpace : GreenSpace
    +equals(Object o) : boolean
}

class "GreenSpaceMapper" {
    +objectToDTO(greenSpace : GreenSpace) : GreenSpaceDTO
    +DTOToObject(greenSpaceDTO : GreenSpaceDTO) : GreenSpace
    +objectListToDTOList(greenSpaceList : Optional<ArrayList<GreenSpace>>) : Optional<ArrayList<GreenSpaceDTO>>
    +getMapper() : GreenSpaceMapper
}

class "RegisterGreenSpaceUI" {
    -name : String
    -address : String
    -area : int
    -type : GreenSpaceType
    -registerGreenSpaceController : RegisterGreenSpaceController
    +getRegisterGreenSpaceController() : RegisterGreenSpaceController

}

RegisterGreenSpaceController ..> GreenSpaceRepository : greenSpaceRepository
RegisterGreenSpaceController ..> GreenSpace : greenSpace
GreenSpace ..> GreenSpaceRepository : exists in >
RegisterGreenSpaceUI ..> RegisterGreenSpaceController : controller
RegisterGreenSpaceUI ..> GreenSpaceDTO : greenSpaceDTO
GreenSpaceMapper ..> GreenSpaceDTO : greenSpaceDTO
GreenSpaceDTO ..> GreenSpaceMapper : mapper
GreenSpaceMapper ..> GreenSpace : greenSpace
GreenSpace ..> GreenSpaceMapper : mapper



class RegisterGreenSpaceUI {

    - registerGreenSpaceController: RegisterGreenSpaceController

    + getRegisterGreenSpaceController(): RegisterGreenSpaceController

}

RegisterGreenSpaceController --> GreenSpaceRepository
RegisterGreenSpaceController --> GreenSpace
GreenSpaceRepository --> GreenSpace
RegisterGreenSpaceUI --> RegisterGreenSpaceController
@enduml
