@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":GreenSpaceRepository" as REPO
participant ":GreenSpaceMapper" as MAP
participant "Repositories" as RepositorySingleton
participant "GreenSpaceDTO" as DTO
participant "GreenSpace" as GS

activate GSM
    GSM -> "UI" : asks to register a new green space
    activate System


    UI --> GSM : request details of the green space(garden, medium-sized park or large-sized park)\n and respctive area
    deactivate System

    GSM -> UI : provides green space details


UI -> GSM : requests data (name, address, area, type)
deactivate UI
UI -> CTRL : createGreenSpace(name, address, area, type)
activate CTRL

CTRL -> RepositorySingleton : getGreenSpaceRepository()
activate RepositorySingleton

RepositorySingleton --> CTRL : GreenSpaceRepository instance
deactivate RepositorySingleton

CTRL -> MAP : objectToDTO(name, address, area, type)
activate MAP

MAP -> DTO : create(name, address, area, type)
activate DTO

DTO --> MAP : GreenSpaceDTO instance
deactivate DTO

MAP --> CTRL : GreenSpaceDTO
deactivate MAP

CTRL -> REPO : add(GreenSpaceDTO)
activate REPO

REPO -> GS : create(GreenSpaceDTO)
activate GS
deactivate GS

REPO --> CTRL : Optional<GreenSpace>
deactivate REPO

CTRL --> UI : registration result
deactivate CTRL

UI --> GSM : shows registration result
deactivate UI

deactivate GSM

@enduml
