@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class GreenSpace{
    local
    address
    area
}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Vehicle {
    plate number
    brand
    type
    model
    current km
    checkup frequency
    km at last checkup
}

class Checkup {
    current vehicle km
    vehicle plate number
}

class FleetManager {
    name
    email
    phone
}

class HumanResourcesManager {
    name
    email
    phone
}

class GreenSpaceManager {
    name
    email
    phone
}

class GreenSpaceUser {
    name
    email
}

class Collaborator {
    name
    birthdate
    admission date
    address
    email
    phone
}

class ID {
    type
    number
}

class Job {
    name
}

class Skill {
    name
}

class Team {
    numberOfCollaborators
}

class Task {
    name
    description
}

Organization "1" - "*" Collaborator : has >
Organization "1" - "1" FleetManager : has >
Organization "1" - "1" HumanResourcesManager : has >
Organization "1" - "1" GreenSpaceManager : has >
Organization "1" - "*" GreenSpace : owns >
GreenSpaceManager "1" - "1" GreenSpace : manages >
GreenSpaceManager "1" - "1" FleetManager : employs >
GreenSpaceManager "1" - "1" HumanResourcesManager : employs >
GreenSpaceUser "*" - "1" GreenSpace : uses >
Organization "1" - "*" Vehicle: owns >
Vehicle "1" - "*" Checkup: undergoes >
HumanResourcesManager "1" - "*" Collaborator : manages >
Collaborator "1" -- "0..*" Vehicle : uses >
HumanResourcesManager "1" -- "*" Skill : registers >
HumanResourcesManager "1" -- "*" Job : registers >
Collaborator "1" -- "*" Skill : has >
Collaborator "1" -- "1" Job : has >
Collaborator "1" -- "1" ID : has >
FleetManager "1" -- "*" Vehicle : maintains >
FleetManager "1" -- "*" Checkup : orders >
Team "1" -- "1" Task : carries out >
Team "1" -- "*" Skill : requires a set of >
Collaborator "*" -- "1" Team : form >

@enduml