@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods


class GreenSpace{
    local
    address
    area
}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}
class GreenSpaceManager {
    name
    email
    phone
}
Organization "1" -up- "1" GreenSpaceManager : has >
Organization "1" -up- "*" GreenSpace : owns >
GreenSpaceManager "1" - "1" GreenSpace : manages >
@enduml