@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space \nManager" as ADM
participant ":AddTaskEntryUI" as UI
participant ":AddTaskEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":repositories\n:Repositories" as PLAT

participant ":UrgencyLevelRepository" as URG
participant ":ToDoListRepository" as TDR
participant "taskEntry\n:TaskEntry" as TASK

activate ADM

    ADM -> UI : asks to add a new entry to the To-Do List
    activate UI

        UI -> CTRL : getUrgencyLevelList()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getUrgencyLevelRepository()
            activate PLAT

                PLAT --> CTRL : UrgencyLevelRepository
            deactivate PLAT

            CTRL -> URG : getUrgencyLevelList()
            activate URG

                URG --> CTRL : UrgencyLevelList
            deactivate URG

            CTRL --> UI : UrgencyLevelList
        deactivate CTRL

        UI --> ADM : shows a list of degrees of urgency and asks to select one (UrgencyLevelList)
    deactivate UI

    ADM -> UI : selects a urgency level
    activate UI

        UI --> ADM : requests data (taskDescription, taskDuration)
    deactivate UI

    ADM -> UI : types data
    activate UI

        UI --> ADM : shows all data and requests confirmation (taskDescription, taskDuration, UrgencyLevel)
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : addTask(taskDescription, taskDuration, UrgencyLevel)
        activate CTRL

            CTRL -> PLAT : getToDoListRepository()
            activate PLAT

                PLAT --> CTRL : toDoListRepository
            deactivate PLAT

            CTRL -> TDR : addTask(taskDescription, taskDuration, UrgencyLevel)
            activate TDR

                TDR -> TASK** : createTask(taskDescription, taskDuration, UrgencyLevel)
                TDR --> TDR : validateEntry(entry)
                TDR --> TDR : saveEntry(entry)
                TDR --> CTRL : boolean
            deactivate TDR

            CTRL --> UI : boolean
        deactivate CTRL

        UI --> ADM : displays operation success
    deactivate UI

deactivate ADM

@enduml