@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class PostponeTaskUI{
}


class PostponeTaskController{
-AgendaRepository agendaRepository
    + PostponeTaskController(agendaRepository)
    + getPlannedAndPostponedTask()
 }

class Repositories {
    - Repositories(): Repositories
    + getInstance() : Repositories
    + getAgendaRepository() : Repositories
}


class AgendaRepository {
    + getPlannedAndPostponedTask()

}

class  TaskEntry{
        -title
        -description
        -urgencyLevel
        -expectedDuration
        -state
        -greenSpace

}

class TaskEntryMapper{
+TaskEntryDto  toDTO(TaskEntry)
}
class TaskEntryDto{
+TaskEntry
+Date
+Time
}


PostponeTaskUI .>  PostponeTaskController
PostponeTaskController ...r> Repositories : repositories
PostponeTaskController ...> TaskEntryMapper : Mapper
TaskEntryMapper ...> TaskEntryDto: TaskEntryDto
TaskEntryMapper ...> TaskEntry
PostponeTaskUI .> TaskEntryDto
PostponeTaskController ..> TaskEntryDto
Repositories ---> "1" AgendaRepository
Repositories -> Repositories : instance
Repositories "1" --> "*" TaskEntry

AgendaRepository --> "*" TaskEntry: contains

 PostponeTaskController ......>  TaskEntry : TaskEntry
 PostponeTaskController ...> "1" AgendaRepository : AgendaRepository
@enduml