@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "CollaboratorsRepository" as CollaboratorsRepository
participant "Colaborator" as Collaborator

autonumber 25
-> CollaboratorsRepository: assignSkill(collaboratorName, skillName)

autonumber 25.1
activate CollaboratorsRepository
    group Assign Skills

        CollaboratorsRepository -> Collaborator**: assignSkill(collaboratorName, skillName)
    activate Collaborator
        Collaborator -> Collaborator: validateSkill(skillName)

        Collaborator -> Collaborator : assignSkill(skillName)

     Collaborator --> CollaboratorsRepository : skill
             deactivate Collaborator

    end

        autonumber 26
         <-- CollaboratorsRepository : skill




@enduml