@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":GetGreenSpacesManagedByUserUI" as UI
participant ":AuthenticationRepository" as AuthenticationRepository
participant ":GreenSpaceController" as GreenSpaceController
participant ":GreenRepositories" as GreenSpaceRepositories
participant "repositories:\nRepositoriesInstance" as RepositoriesInstance
participant "GreenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "GreenSpace" as GreenSpace
participant "GreenSpaceDTO" as GreenSpaceDTO
participant "GreenSpaceMapper" as GreenSpaceMapper

activate GSM

GSM -> UI : requests to list green spaces managed by GSM

activate UI

UI -> AuthenticationRepository : getCurrentUserSession().getUserId().getEmail()
activate AuthenticationRepository
AuthenticationRepository --> UI : email
deactivate AuthenticationRepository

UI -> GreenSpaceController : listGreenSpaces(email)
activate GreenSpaceController

GreenSpaceController -> Repositories : getInstance()
activate Repositories
Repositories --> GreenSpaceController : instance
deactivate Repositories

GreenSpaceController -> RepositoriesInstance : GreenSpaceRepository()
activate RepositoriesInstance
RepositoriesInstance --> GreenSpaceController : GreenSpaceRepository
deactivate RepositoriesInstance

GreenSpaceController -> GreenSpaceRepository : GetGreenSpacesManagedByUserController
activate GreenSpaceRepository
GreenSpaceRepository --> GreenSpaceController : greenSpaces
deactivate GreenSpaceRepository

GreenSpaceController -> GreenSpaceMapper : GreenSpaceDTO(greenSpaces)
activate GreenSpaceMapper
GreenSpaceMapper --> GreenSpaceController : GreenSpaceDTOs
deactivate GreenSpaceMapper

GreenSpaceController -> GreenSpaceController : sortGreenSpacesBySizeDescending(GreenSpaceDTOs, "configFile")

GreenSpaceController --> UI : sortedGreenSpaceDTOs
deactivate GreenSpaceController

UI --> GSM : displays sorted green spaces
deactivate UI
deactivate GSM

@enduml
