@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Cancel Task in Agenda

autonumber

actor "Green Space\nManager" as Manager
participant ":System" as System

activate GSM

GSM -> System : requests to view planned and postponed tasks
activate System

    System --> GSM : displays list of planned and postponed tasks
deactivate System

GSM -> System : selects a task to cancel
activate System

    System --> GSM : confirms task cancellation
deactivate System

GSM -> System : confirms cancellation
activate System

    System --> GSM : displays task cancellation success
deactivate System
@enduml