@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction
class RegisterCollaboratorUI {
}

class RegisterCollaboratorController {
    + RegisterCollaboratorController(jobRepository, collaboratorRepository)
    + getListJob()
    + createCollaborator(name,birthdate,admission date,address,phone number,email,identification document type,identification number)

}
class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobRepository()
    + getCollaboratorRepository()
}

class JobRepository {
    + getJobList()
    + getJob(job)
}

class CollaboratorRepository {
    + getCollaboratorList()
}

class Collaborator{
- String name
- String birthdate
- String admission date
- String address
- String email
- String skill
- int phone
}







Repositories -> Repositories : instance
RegisterCollaboratorUI .> RegisterCollaboratorController
RegisterCollaboratorController .> Repositories : repositories
Repositories -> "1" JobRepository
RegisterCollaboratorController ..> CollaboratorRepository : CollaboratorRepository
RegisterCollaboratorController ..> JobRepository : JobRepository
JobRepository ..> Collaborator
CollaboratorRepository -> Collaborator: has
Repositories --> "1" CollaboratorRepository


@enduml