@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Green Space\nManager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : asks to add a new entry in the Agenda
    activate System

        System --> Manager : requests data(i.e. starting date)
         deactivate System

    Manager -> System : types requested data
    activate System

          System --> Manager : displays all the entries
          deactivate System

    Manager -> System : choose one of the entries
    activate System

          System --> Manager : requests confirmation
          deactivate System

    Manager -> System : confirms entry
    activate System

    System --> Manager : displays operation success

@enduml