@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CancelTaskUI{
}


class CancelTaskController{
-AgendaRepository agendaRepository
    + CancelTaskController(agendaRepository)
    + cancelTask(taskEntryDto)
    + getPlannedAndPostponedTask()
 }

class Repositories {
    - Repositories(): Repositories
    + getInstance() : Repositories
    + getAgendaRepository() : Repositories
}


class AgendaRepository {
    + getPlannedAndPostponedTask()

}

class  TaskEntry{
        -title
        -description
        -urgencyLevel
        -expectedDuration
        -state
        -greenSpace

}

class TaskEntryMapper{
+TaskEntryDto  toDTO(TaskEntry)
}
class TaskEntryDto{
+TaskEntry
+Date
+Time
}


CancelTaskUI .>  CancelTaskController
CancelTaskController ...r> Repositories : repositories
CancelTaskController ...> TaskEntryMapper : Mapper
TaskEntryMapper ...> TaskEntryDto: TaskEntryDto
TaskEntryMapper ...> TaskEntry
CancelTaskUI .> TaskEntryDto
CancelTaskController ..> TaskEntryDto
Repositories ---> "1" AgendaRepository
Repositories -> Repositories : instance
Repositories "1" --> "*" TaskEntry

AgendaRepository --> "*" TaskEntry: contains

 CancelTaskController ......>  TaskEntry : TaskEntry
 CancelTaskController ...> "1" AgendaRepository : AgendaRepository
@enduml