@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Main Solution

autonumber

actor "Collaborator" as Manager
participant ":System" as System

activate Manager

    Manager -> System : asks to record the completion of a task.
    activate System

        System --> Manager : presents current user tasks list
    deactivate System
    Manager -> System : selects a task
    activate System

        System --> Manager : displays operation success message

@enduml